# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'program_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(436, 600))
        MainWindow.setMaximumSize(QtCore.QSize(436, 600))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setToolTipDuration(0)
        MainWindow.setStatusTip("")
        # MainWindow.setStyleSheet("background-color:#5B5B5B;\n")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.savebutton = QtWidgets.QPushButton(self.centralwidget)
        self.savebutton.setGeometry(QtCore.QRect(140, 550, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.savebutton.setFont(font)
        # self.savebutton.setStyleSheet("background-color: rgb(75, 75, 75);\n"
        #                              "color: rgb(255, 255, 255);\n"
        #                              "selection-color: rgb(255, 255, 255);")
        self.savebutton.setObjectName("savebutton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 431, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        # self.label_8.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.sex_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.sex_comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        # self.sex_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sex_comboBox.setCurrentText("")
        self.sex_comboBox.setObjectName("sex_comboBox")
        self.sex_comboBox.addItem("")
        self.sex_comboBox.setItemText(0, "")
        self.sex_comboBox.addItem("")
        self.sex_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.sex_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        # self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.secondname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.secondname.setMaximumSize(QtCore.QSize(270, 16777215))
        # self.secondname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.secondname.setObjectName("secondname")
        self.horizontalLayout_3.addWidget(self.secondname)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        # self.label_3.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name.setMaximumSize(QtCore.QSize(270, 16777215))
        # self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.horizontalLayout_4.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        # self.label_4.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.patronymic = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.patronymic.setMaximumSize(QtCore.QSize(270, 16777215))
        # self.patronymic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.patronymic.setObjectName("patronymic")
        self.horizontalLayout_5.addWidget(self.patronymic)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Job = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Job.setFont(font)
        # self.Job.setStyleSheet("color: rgb(255, 255, 255)")
        self.Job.setObjectName("Job")
        self.horizontalLayout_6.addWidget(self.Job)
        self.post = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.post.setMaximumSize(QtCore.QSize(270, 16777215))
        # self.post.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.post.setObjectName("post")
        self.horizontalLayout_6.addWidget(self.post)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        # self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.phoneNumber = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.phoneNumber.setMaximumSize(QtCore.QSize(270, 16777215))
        # self.phoneNumber.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phoneNumber.setMaxLength(15)
        self.phoneNumber.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.phoneNumber.setObjectName("phoneNumber")
        self.horizontalLayout_2.addWidget(self.phoneNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        # self.label_11.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.professional_skills = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.professional_skills.setMaximumSize(QtCore.QSize(270, 50))
        # self.professional_skills.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.professional_skills.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.professional_skills.setTabChangesFocus(True)
        self.professional_skills.setObjectName("professional_skills")
        self.horizontalLayout_7.addWidget(self.professional_skills)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        # self.label_6.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.email.setMaximumSize(QtCore.QSize(270, 16777215))
        # self.email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email.setObjectName("email")
        self.horizontalLayout_8.addWidget(self.email)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        # self.label_5.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.birthDate = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.birthDate.setMaximumSize(QtCore.QSize(200, 16777215))
        # self.birthDate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.birthDate.setObjectName("birthDate")
        self.horizontalLayout_10.addWidget(self.birthDate)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        # self.label_12.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.personal_qualities = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.personal_qualities.setMaximumSize(QtCore.QSize(270, 50))
        # self.personal_qualities.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.personal_qualities.setTabChangesFocus(True)
        self.personal_qualities.setDocumentTitle("")
        self.personal_qualities.setObjectName("personal_qualities")
        self.horizontalLayout_11.addWidget(self.personal_qualities)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setToolTip("")
        self.label_7.setToolTipDuration(0)
        # self.label_7.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.edu_level = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.edu_level.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edu_level.setToolTipDuration(23)
        # self.edu_level.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edu_level.setObjectName("edu_level")
        self.edu_level.addItem("")
        self.edu_level.setItemText(0, "")
        self.edu_level.addItem("")
        self.edu_level.addItem("")
        self.edu_level.addItem("")
        self.edu_level.addItem("")
        self.horizontalLayout_12.addWidget(self.edu_level)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        # self.label_9.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.experience = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.experience.setMaximumSize(QtCore.QSize(270, 60))
        # self.experience.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.experience.setTabChangesFocus(True)
        self.experience.setObjectName("experience")
        self.horizontalLayout_13.addWidget(self.experience)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.Addphoto = QtWidgets.QPushButton(self.centralwidget)
        self.Addphoto.setGeometry(QtCore.QRect(230, 470, 201, 61))
        # self.Addphoto.setStyleSheet("background-color:rgb(75,75,75);\n"
        #                             "color: rgb(255, 255, 255)")
        self.Addphoto.setObjectName("Addphoto")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Резюмейкер"))
        self.savebutton.setText(_translate("MainWindow", "Сохранить резюме"))
        self.label_8.setText(_translate("MainWindow", "Пол"))
        self.sex_comboBox.setItemText(1, _translate("MainWindow", "Мужской"))
        self.sex_comboBox.setItemText(2, _translate("MainWindow", "Женский"))
        self.label_2.setText(_translate("MainWindow", "Фамилия"))
        self.secondname.setPlaceholderText(_translate("MainWindow", "Иванов"))
        self.label_3.setText(_translate("MainWindow", "Имя "))
        self.name.setPlaceholderText(_translate("MainWindow", "Иван"))
        self.label_4.setText(_translate("MainWindow", "Отчество "))
        self.patronymic.setPlaceholderText(_translate("MainWindow", "Иванович"))
        self.Job.setText(_translate("MainWindow", "Должность"))
        self.post.setPlaceholderText(_translate("MainWindow", "Программист"))
        self.label.setText(_translate("MainWindow", "Телефон"))
        self.phoneNumber.setInputMask(_translate("MainWindow", "8(999)999-99-99"))
        self.phoneNumber.setPlaceholderText(_translate("MainWindow", "88005553535"))
        self.label_11.setText(_translate("MainWindow", "<html><head></head><Style> \n"
"p{\n"
"line-height: 0.4;\n"
"\n"
"\n"
"\n"
"}\n"
"</Style>\n"
"\n"
"\n"
"\n"
"\n"
"<body><p>Профессиональные </p><p align=\"justify\">навыки </p><p><br/></p></body></html>"))
        self.professional_skills.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.professional_skills.setPlaceholderText(_translate("MainWindow", "Свободное владение ПК, опыт разработки программного обеспечения и т.д."))
        self.label_6.setText(_translate("MainWindow", "E-mail"))
        self.email.setPlaceholderText(_translate("MainWindow", "ivanovivan1982@yandex.ru"))
        self.label_5.setText(_translate("MainWindow", "Дата рождения"))
        self.label_12.setText(_translate("MainWindow", "Личные качества"))
        self.personal_qualities.setPlaceholderText(_translate("MainWindow", "Трудолюбие, внимательность, исполнительность, стрессоустойчивость и т.д."))
        self.label_7.setText(_translate("MainWindow", "Уровень образования"))
        self.edu_level.setItemText(1, _translate("MainWindow", "Среднее"))
        self.edu_level.setItemText(2, _translate("MainWindow", "Среднее специальное"))
        self.edu_level.setItemText(3, _translate("MainWindow", "Неполное высшее"))
        self.edu_level.setItemText(4, _translate("MainWindow", "Высшее"))
        self.label_9.setText(_translate("MainWindow", "Опыт работы"))
        self.experience.setPlaceholderText(_translate("MainWindow", "Пример: Веб-программист апрель 2008 г. – июль 2010 г. ОАО «Телетрейд консалтинг», г. Борисполь. Функциональные обязанности: разработка и поддержка сайтов"))
        self.Addphoto.setText(_translate("MainWindow", "Приложить личное фото"))
